In [2]:
# Initial imports
import pandas as pd
from pathlib import Path

In [5]:
csv_path = Path("data/dwelling_types_syd_LGA.csv")
dwelling_types_syd_LGA_df = pd.read_csv(csv_path, index_col="Local Government Areas")
dwelling_types_syd_LGA_df.head()

,Separate house,"Semi-detached, row or terrace house, townhouse etc with one storey","Semi-detached, row or terrace house, townhouse etc with two or more storeys","Flat, unit or apartment in a one or two storey block","Flat, unit or apartment in a three storey block","Flat, unit or apartment in a four or more storey block","Flat, unit or apartment attached to a house",Total
Local Government Areas,,,,,,,,
Rockdale (C),18402,3623,1333,2923,5371,5939,93,37679
Blacktown (C),77966,4762,5301,1419,1711,1356,112,92622
Burwood (A),6300,744,389,1035,1647,1414,16,11551
Camden (A),15882,435,199,272,0,0,32,16817
Campbelltown (C),40117,4450,4029,1062,225,220,18,50120

In [3]:
# Check for null values
dwelling_types_syd_LGA_df.isnull()

,Local Government Areas,Separate house,"Semi-detached, row or terrace house, townhouse etc with one storey","Semi-detached, row or terrace house, townhouse etc with two or more storeys","Flat, unit or apartment in a one or two storey block","Flat, unit or apartment in a three storey block","Flat, unit or apartment in a four or more storey block","Flat, unit or apartment attached to a house",Total
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False

In [4]:
# Determine number of nulls
dwelling_types_syd_LGA_df.isnull().sum()

Local Government Areas                                                         0
Separate house                                                                 0
Semi-detached, row or terrace house, townhouse etc with one storey             0
Semi-detached, row or terrace house, townhouse etc with two or more storeys    0
Flat, unit or apartment in a one or two storey block                           0
Flat, unit or apartment in a three storey block                                0
Flat, unit or apartment in a four or more storey block                         0
Flat, unit or apartment attached to a house                                    0
Total                                                                          0
dtype: int64

In [5]:
# Check duplicates
dwelling_types_syd_LGA_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
dtype: bool

In [6]:
csv_path = Path("data/tenure_type_syd_LGA.csv")
tenure_type_syd_LGA_df = pd.read_csv(csv_path, index_col="Local Government Areas")
tenure_type_syd_LGA_df.head()

,Fully owned,Being purchased,Being purchased under a rent/buy scheme,Rented,Total
Local Government Areas,,,,,
Rockdale (C),12312,8713,61,10287,31368
Blacktown (C),20946,35383,229,26029,82582
Burwood (A),3701,2399,33,3625,9753
Camden (A),4042,8107,19,2961,15136
Campbelltown (C),10842,19076,111,14252,44288

In [7]:
# Check for null values
tenure_type_syd_LGA_df.isnull()

,Local Government Areas,Fully owned,Being purchased,Being purchased under a rent/buy scheme,Rented,Total
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False

In [8]:
# Determine number of nulls
tenure_type_syd_LGA_df.isnull().sum()

Local Government Areas                     0
Fully owned                                0
Being purchased                            0
Being purchased under a rent/buy scheme    0
Rented                                     0
Total                                      0
dtype: int64

In [9]:
# Check duplicates
tenure_type_syd_LGA_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
dtype: bool

In [7]:
csv_path = Path("data/Loan_repay_range_syd_LGA.csv")
Loan_repay_range_syd_LGA_df = pd.read_csv(csv_path, index_col="Local Government Areas")
Loan_repay_range_syd_LGA_df.head()

,$1 - $99,$100 - $149,$150 - $249,$250 - $399,$400 - $549,$550 - $649,$650 - $749,$750 - $849,$850 - $949,"$950 - $1,049",...,"$1,200 - $1,399","$1,400 - $1,599","$1,600 - $1,999","$2,000 - $2,399","$2,400 - $2,999","$3,000 - $3,999","$4,000 and over",Not stated,Not applicable,Total
Local Government Areas,,,,,,,,,,,,,,,,,,,,,
Rockdale (C),50,18,59,125,224,83,187,179,266,300,...,658,630,1320,1266,947,871,479,754,29291,38067
Blacktown (C),223,92,224,485,1006,524,932,825,1224,1333,...,3100,2875,6192,5745,3723,1912,796,2505,57882,93496
Burwood (A),15,0,17,35,74,31,42,58,66,74,...,173,153,320,353,248,269,183,232,9229,11663
Camden (A),30,10,36,91,165,110,157,161,253,258,...,674,579,1476,1372,1012,587,239,551,8852,16980
Campbelltown (C),80,52,174,275,684,374,648,594,929,895,...,1955,1860,3484,2501,1110,613,322,1307,31079,50265

In [18]:
# Check for null values
Loan_repay_range_syd_LGA_df.isnull()

,Local Government Areas,$1 - $99,$100 - $149,$150 - $249,$250 - $399,$400 - $549,$550 - $649,$650 - $749,$750 - $849,$850 - $949,...,"$1,200 - $1,399","$1,400 - $1,599","$1,600 - $1,999","$2,000 - $2,399","$2,400 - $2,999","$3,000 - $3,999","$4,000 and over",Not stated,Not applicable,Total
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
# Determine number of nulls
Loan_repay_range_syd_LGA_df.isnull().sum()

Local Government Areas    0
$1 - $99                  0
$100 - $149               0
$150 - $249               0
$250 - $399               0
$400 - $549               0
$550 - $649               0
$650 - $749               0
$750 - $849               0
$850 - $949               0
$950 - $1,049             0
$1,050 - $1,199           0
$1,200 - $1,399           0
$1,400 - $1,599           0
$1,600 - $1,999           0
$2,000 - $2,399           0
$2,400 - $2,999           0
$3,000 - $3,999           0
$4,000 and over           0
Not stated                0
Not applicable            0
Total                     0
dtype: int64

In [13]:
# Check duplicates
Loan_repay_range_syd_LGA_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
dtype: bool

In [8]:
csv_path = Path("data/rent_range_syd_LGA.csv")
rent_range_syd_LGA_df = pd.read_csv(csv_path, index_col="Local Government Areas")
rent_range_syd_LGA_df.head()

,$0-$49,$50-$74,$75-$99,$100-$119,$120-$139,$140-$159,$160-$179,$180-$199,$200-$224,$225-$249,$250-$274,$275-$299,$300-$349,$350-$449,$450-$549,$550andover,Not stated,Not applicable,Total
Local Government Areas,,,,,,,,,,,,,,,,,,,
Rockdale (C),338,315,163,200,167,171,213,435,1382,1157,1414,893,1793,1253,207,167,298,27501,38067
Blacktown (C),666,2046,1398,1387,1057,1052,1529,2405,4374,3236,2856,880,1196,933,126,312,1032,67007,93496
Burwood (A),147,148,69,67,52,49,77,111,272,232,426,351,789,628,140,81,127,7913,11663
Camden (A),128,113,55,68,58,96,64,81,269,445,598,243,430,283,45,18,88,13915,16980
Campbelltown (C),370,1187,1081,890,676,818,1358,1746,2753,1301,944,254,269,156,27,131,533,35788,50265

In [15]:
# Check for null values
rent_range_syd_LGA_df.isnull()

,Local Government Areas,$0 - $49,$50 - $74,$75 - $99,$100 - $119,$120 - $139,$140 - $159,$160 - $179,$180 - $199,$200 - $224,$225 - $249,$250 - $274,$275 - $299,$300 - $349,$350 - $449,$450 - $549,$550 and over,Not stated,Not applicable,Total
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
# Determine number of nulls
rent_range_syd_LGA_df.isnull().sum()

Local Government Areas    0
$0 - $49                  0
$50 - $74                 0
$75 - $99                 0
$100 - $119               0
$120 - $139               0
$140 - $159               0
$160 - $179               0
$180 - $199               0
$200 - $224               0
$225 - $249               0
$250 - $274               0
$275 - $299               0
$300 - $349               0
$350 - $449               0
$450 - $549               0
$550 and over             0
Not stated                0
Not applicable            0
Total                     0
dtype: int64

In [17]:
# Check duplicates
rent_range_syd_LGA_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
dtype: bool